version: "3"

services:
  giseye:
    container_name: giseye
    build: .
    entrypoint: npm run start
    environment:
      - REACT_APP_FETCH_TIMEOUT=${REACT_APP_FETCH_TIMEOUT}
      - REACT_APP_MAPBOX_API_KEY=${REACT_APP_MAPBOX_API_KEY}
    volumes:
     - ./app/public:/home/node/app/public
     - ./app/src:/home/node/app/src
    ports:
      - "${HTTP_DEV_PORT}:3000"