version: "3"

services:
  giseye:
    container_name: giseye
    build: .
    entrypoint: npm run build
    env_file:
      - .env
    volumes:
     - ./app/public:/home/node/app/public
     - ./app/src:/home/node/app/src
     - ./app/build:/home/node/app/build
    ports:
      - "${HTTP_DEV_PORT}:3000"